import VICSModule from '../studio/VICSModule';
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ShieldCheck, Lock, Eye, EyeOff, CheckCircle2, AlertCircle, Info, Shield, Zap, Fingerprint } from 'lucide-react';

export default function VICSProtocol() {
  const [isOptedIn, setIsOptedIn] = useState(false);
  const [showProtocolDetails, setShowProtocolDetails] = useState(false);

  return (
    <div className="space-y-24 pb-32">
      {/* Hero Section */}
      <header className="relative">
        <div className="space-y-6 max-w-4xl">
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="flex items-center gap-3"
          >
            <div className="h-[1px] w-12 bg-velvet-purple/50" />
            <span className="micro-label !text-velvet-purple">Ethical AI Governance</span>
          </motion.div>
          
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-6xl md:text-8xl font-serif font-bold italic tracking-tighter text-white leading-[0.9]"
          >
            VICS <br/> 
            <span className="premium-gradient-text">Protocol</span>
          </motion.h1>
          
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-xl text-slate-500 max-w-2xl leading-relaxed font-serif italic"
          >
            The Vocal Identity & Consent Steward (VICS) ensures that every biometric artifact generated by The Empire is legally cleared, cryptographically anchored, and ethically sound.
          </motion.p>
        </div>
      </header>

      <VICSModule />

      {/* Opt-in Biometric Privacy Protocol */}
      <section className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-7 space-y-12">
          <div className="space-y-6">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-velvet-purple/10 rounded-xl border border-velvet-purple/20">
                <Fingerprint className="w-6 h-6 text-velvet-purple" />
              </div>
              <h2 className="text-3xl font-serif font-bold italic text-white">Biometric Privacy <br/><span className="text-slate-500">Architecture</span></h2>
            </div>
            
            <p className="text-lg text-slate-500 leading-relaxed font-serif italic">
              We utilize a "Zero-Knowledge Phonation" architecture where your raw biometric data is never stored—only the mathematical "Soulfire" vectors are preserved.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[
              { title: 'Consent Matrix', desc: 'Granular control over which Soulfire agents can utilize your vocal primitives.', icon: Shield },
              { title: 'DNA Anchoring', desc: 'Every artifact is signed with your unique VICS DNA Tag for permanent attribution.', icon: Zap }
            ].map((item, i) => (
              <div key={i} className="p-8 bg-white/[0.02] border border-white/5 rounded-3xl hover:bg-white/[0.05] transition-all group">
                <item.icon className="w-6 h-6 text-slate-600 group-hover:text-velvet-purple mb-4 transition-colors" />
                <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-2">{item.title}</h4>
                <p className="text-xs text-slate-500 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>

          <div className="space-y-4">
            <button 
              onClick={() => setShowProtocolDetails(!showProtocolDetails)}
              className="micro-label !text-velvet-purple flex items-center gap-2 hover:opacity-80 transition-opacity"
            >
              <Info className="w-4 h-4" />
              {showProtocolDetails ? 'Hide' : 'View'} Technical Protocol
            </button>

            <AnimatePresence>
              {showProtocolDetails && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="overflow-hidden"
                >
                  <div className="p-8 bg-black/40 rounded-3xl border border-white/5 font-mono text-[10px] text-slate-600 leading-relaxed">
                    <div className="text-velvet-purple mb-4 font-bold uppercase tracking-widest">[PROTOCOL_v1.0.4_STABLE]</div>
                    1. BIOMETRIC_INGESTION: Raw PCM (48kHz) {'->'} FFT {'->'} Affective Vector Extraction.<br/>
                    2. DATA_PURGE: Immediate deletion of raw PCM post-extraction.<br/>
                    3. VECTOR_ENCRYPTION: AES-256 GCM with Creator-held keys.<br/>
                    4. CONSENT_VERIFICATION: Smart contract call to VICS_REGISTRY before any synthesis event.<br/>
                    5. ATTRIBUTION: Automatic royalty routing via Pulse-Stream Broker.
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>

        <div className="lg:col-span-5">
          <div className="glass-card p-12 flex flex-col items-center text-center space-y-8 border-white/10 relative overflow-hidden group">
            <div className="absolute inset-0 bg-gradient-to-b from-velvet-purple/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
            
            <div className={`w-24 h-24 rounded-full flex items-center justify-center transition-all duration-700 relative ${isOptedIn ? 'bg-velvet-purple/20 text-velvet-purple shadow-[0_0_40px_rgba(124,58,237,0.3)]' : 'bg-white/5 text-slate-600'}`}>
              {isOptedIn ? <Eye className="w-12 h-12" /> : <EyeOff className="w-12 h-12" />}
              {isOptedIn && (
                <motion.div 
                  layoutId="glow"
                  className="absolute inset-0 bg-velvet-purple/20 blur-2xl rounded-full"
                />
              )}
            </div>
            
            <div className="space-y-3 relative z-10">
              <h3 className="text-2xl font-serif font-bold italic text-white">Biometric Opt-in</h3>
              <p className="text-sm text-slate-500 leading-relaxed font-serif italic">
                Toggle to authorize the S2 Engine to utilize your vocal primitives for metamorphic blending.
              </p>
            </div>

            <button 
              onClick={() => setIsOptedIn(!isOptedIn)}
              className={`w-full py-5 rounded-2xl font-bold uppercase tracking-[0.3em] text-[10px] transition-all duration-500 relative z-10 ${isOptedIn ? 'bg-velvet-purple text-white shadow-[0_20px_40px_-10px_rgba(124,58,237,0.4)]' : 'bg-white/5 text-slate-500 hover:bg-white/10'}`}
            >
              {isOptedIn ? 'Authorized' : 'Authorize Now'}
            </button>

            {isOptedIn && (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex items-center gap-2 text-[10px] font-bold text-emerald-500 uppercase tracking-widest"
              >
                <ShieldCheck className="w-4 h-4" />
                Cryptographic Consent Active
              </motion.div>
            )}
          </div>
        </div>
      </section>
      
      <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="p-10 bg-white/[0.02] border border-white/5 rounded-[2.5rem] space-y-4">
          <h3 className="text-xl font-serif font-bold italic text-white">Secure Consent Management</h3>
          <p className="text-slate-500 text-sm leading-relaxed">
            Our smart contract infrastructure automates outreach to estates and living artists. Once consent is granted, the "Voice DNA" is hashed onto the Empire 1 Ledger, ensuring a permanent, immutable record of authorization.
          </p>
        </div>
        <div className="p-10 bg-white/[0.02] border border-white/5 rounded-[2.5rem] space-y-4">
          <h3 className="text-xl font-serif font-bold italic text-white">Persona Cultivation</h3>
          <p className="text-slate-500 text-sm leading-relaxed">
            Instead of cloning identities, we cultivate personas. By adjusting the "Vocal DNA" sliders, users can blend archetypal characteristics—like Chalino's grit or Ramon's phrasing—to create entirely new, original vocal expressions.
          </p>
        </div>
      </section>
    </div>
  );
}
