import VICSModule from '../studio/VICSModule';
import { motion } from 'motion/react';
import { ShieldCheck } from 'lucide-react';

export default function VICSProtocol() {
  return (
    <div className="space-y-12">
      <section className="text-center space-y-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-bold uppercase tracking-widest mb-4"
        >
          <ShieldCheck className="w-4 h-4" />
          Ethical AI Governance
        </motion.div>
        <h1 className="text-4xl md:text-6xl font-black text-white tracking-tighter">
          VICS <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-500">PROTOCOL</span>
        </h1>
        <p className="text-neutral-400 max-w-2xl mx-auto text-lg">
          The Vocal Identity & Consent Steward (VICS) ensures that every biometric artifact generated by The Empire is legally cleared, cryptographically anchored, and ethically sound.
        </p>
      </section>

      <VICSModule />
      
      <section className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-12">
        <div className="bg-neutral-900/50 border border-neutral-800 rounded-3xl p-8 space-y-4">
          <h3 className="text-xl font-bold text-white">Secure Consent Management</h3>
          <p className="text-neutral-400 text-sm leading-relaxed">
            Our smart contract infrastructure automates outreach to estates and living artists. Once consent is granted, the "Voice DNA" is hashed onto the Empire 1 Ledger, ensuring a permanent, immutable record of authorization.
          </p>
        </div>
        <div className="bg-neutral-900/50 border border-neutral-800 rounded-3xl p-8 space-y-4">
          <h3 className="text-xl font-bold text-white">Persona Cultivation</h3>
          <p className="text-neutral-400 text-sm leading-relaxed">
            Instead of cloning identities, we cultivate personas. By adjusting the "Vocal DNA" sliders, users can blend archetypal characteristics—like Chalino's grit or Ramon's phrasing—to create entirely new, original vocal expressions.
          </p>
        </div>
      </section>
    </div>
  );
}
