/**
 * Core types for the Sonance Pro AI Music Studio.
 * These types define the structure of the assets generated by the AI agent.
 */

export enum AssetType {
  FULL_TRACK = "full_track",
  STEM = "stem",
  SFX = "sfx",
  AMBIENT = "ambient",
  LOOP = "loop",
}

export enum StemType {
  VOCAL = "vocal",
  DRUMS = "drums",
  BASS = "bass",
  SYNTH = "synth",
  MELODY = "melody",
  HARMONY = "harmony",
  GUITAR = "guitar",
  PIANO = "piano",
  PAD = "pad",
  PERCUSSION = "percussion",
}

export enum SFXCategory {
  FOLEY = "foley",
  UI = "ui",
  TRANSITION = "transition",
  IMPACT = "impact",
  RISER = "riser",
  ATMOSPHERE = "atmosphere",
}

export interface AudioMetadata {
  id: string;
  title: string;
  description?: string;
  type: AssetType;
  stemType?: StemType;
  sfxCategory?: SFXCategory;
  genre?: string;
  bpm?: number;
  key?: string;
  duration: number; // in seconds
  fileUrl: string;
  createdAt: string;
  tags: string[];
  isLoopable: boolean;
  sampleRate: number; // e.g., 48000
  bitDepth: number; // e.g., 24
}

export interface TrackProject {
  id: string;
  title: string;
  masterStyle: string;
  bpm: number;
  key: string;
  fullTrackId?: string;
  stemIds: string[];
  sfxIds: string[];
  createdAt: string;
  updatedAt: string;
}
