/**
 * Core types for the Sonance Pro AI Music Studio.
 * These types define the structure of the assets generated by the AI agent.
 */

export enum AssetType {
  FULL_TRACK = "full_track",
  STEM = "stem",
  SFX = "sfx",
  AMBIENT = "ambient",
  LOOP = "loop",
}

export enum StemType {
  VOCAL = "vocal",
  DRUMS = "drums",
  BASS = "bass",
  SYNTH = "synth",
  MELODY = "melody",
  HARMONY = "harmony",
  GUITAR = "guitar",
  PIANO = "piano",
  PAD = "pad",
  PERCUSSION = "percussion",
}

export enum SFXCategory {
  FOLEY = "foley",
  UI = "ui",
  TRANSITION = "transition",
  IMPACT = "impact",
  RISER = "riser",
  ATMOSPHERE = "atmosphere",
}

export interface AudioMetadata {
  id: string;
  title: string;
  description?: string;
  type: AssetType;
  stemType?: StemType;
  sfxCategory?: SFXCategory;
  genre?: string;
  bpm?: number;
  key?: string;
  duration: number; // in seconds
  fileUrl: string;
  createdAt: string;
  tags: string[];
  isLoopable: boolean;
  sampleRate: number; // e.g., 48000
  bitDepth: number; // e.g., 24
}

export interface Track {
  trackMetadata: {
    title: string;
    core_genre?: string;
    s2_mutation?: string;
    dna_tag_preview?: string;
    [key: string]: unknown;
  };
  acousticPrimitives?: {
    groove?: string;
    texture?: string;
    [key: string]: unknown;
  };
  vocalPipelines?: Array<{ id: string; active: boolean; intensity: number }>;
  audioUrl?: string;
  [key: string]: unknown;
}

export interface MusicAsset {
  id: string;
  name: string;
  createdAt: string;
  category?: string;
  meta: { genre: string; bpm: number; key: string };
  urls: { fullMix?: string; drums?: string; bass?: string; melody?: string; atmosphere?: string; processed?: string; dry?: string; main?: string };
}

export interface VocalAsset {
  id: string;
  name?: string;
  createdAt: string;
  category?: string;
  projectId?: string;
  authorUid?: string;
  meta: { emotionProfile: string; language: string; performerDNA?: Record<string, number>; sections?: unknown[] };
  type: string;
  urls: { processed?: string; dry?: string };
}

export interface SfxAsset {
  id: string;
  name?: string;
  createdAt: string;
  category?: string;
  projectId?: string;
  type?: string;
  authorUid?: string;
  meta: { material: string; environment: string; mass: string | number; frequency: string; envelope?: string };
  urls: { main?: string };
}

export interface AmbientAsset {
  id: string;
  name: string;
  createdAt: string;
  category?: string;
  meta: { elements: string; duration: number; loopable: boolean };
  urls: { main?: string };
}

export interface TrackProject {
  id: string;
  title: string;
  masterStyle: string;
  bpm: number;
  key: string;
  fullTrackId?: string;
  stemIds: string[];
  sfxIds: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: string;
  name: string;
  title?: string;
  ownerId?: string;
  createdAt?: string;
  updatedAt?: string;
}
