import { GoogleGenAI } from "@google/genai";

// Gemini client retained for generateMusicStream (Lyria Realtime streaming).
// translateVibeToParams is now routed through the backend so the key is never
// exposed in the browser bundle.
const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_GEMINI_API_KEY || "" });

const BACKEND_URL: string =
  (process.env.REACT_APP_BACKEND_URL as string) ||
  (import.meta.env.VITE_BACKEND_URL as string) ||
  "";

export interface VibeParams {
  style: string;
  mood: string;
  tempo: number;
  key: string;
  lyrics: string;
  vocalStyle: string;
  // Master Spec Parameters
  engine?: string;
  moodMatrix?: string[];
  genreDNA?: string;
  proceduralSFX?: string;
  vulnerabilitySlider?: number;
  harmonicStructure?: string;
  personaCount?: number;
  personas?: string[];
  // Pro Parameters (Invisible Translation Layer)
  vocalFry?: number;
  inhaleIntensity?: number;
  emotionalBreak?: number;
  roomSize?: number;
  material?: string;
  breathingPattern?: string;
  genreBlend?: string[];
  instrumentation?: string[];
  spatialEffects?: string[];
  harmonicTension?: number;
  vocalLayering?: string;
  mixWarmth?: number;
  reverbType?: string;
  eraTexture?: string;
  emotionalMode?: 'Pain' | 'Playful' | 'Mirror';
  // Advanced Audio Effects
  delayTime?: number;
  delayFeedback?: number;
  chorusDepth?: number;
  phaserRate?: number;
}

export async function translateVibeToParams(vibe: string, context?: { weather?: string, time?: string, heartRate?: number }): Promise<VibeParams> {
  // Route through backend — Gemini key lives server-side only
  const token = localStorage.getItem("lyrica3_token") || "";
  try {
    const res = await fetch(`${BACKEND_URL}/api/vibe/translate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify({ vibe, context }),
    });
    if (!res.ok) throw new Error(`Backend ${res.status}`);
    const data = await res.json();
    if (data.params) return data.params as VibeParams;
  } catch (e) {
    console.warn("translateVibeToParams backend call failed, using defaults:", e);
  }
  // Safe default when backend unreachable
  return {
    style: "Soul / R&B",
    mood: "Melancholic",
    tempo: 90,
    key: "B Minor",
    lyrics: "Two broken smiles in the rain...",
    vocalStyle: "Intimate Confession",
    vocalFry: 0.4,
    inhaleIntensity: 0.6,
    emotionalBreak: 0.3,
    roomSize: 0.5,
    material: "Wood",
    delayTime: 250,
    delayFeedback: 0.3,
    chorusDepth: 0.2,
    phaserRate: 0.5,
  };
}

export async function generateMusicStream(params: VibeParams) {
  try {
    // Using Lyria Clip for 30s preview
    const response = await ai.models.generateContentStream({
      model: "lyria-realtime",
      contents: `Generate a 30-second track. Style: ${params.style}. Mood: ${params.mood}. Tempo: ${params.tempo} BPM. Key: ${params.key}. Vocal Style: ${params.vocalStyle}. Lyrics: ${params.lyrics}`,
    });
    return response;
  } catch (error) {
    console.warn("Lyria model access denied or failed. Falling back to simulated stream with audible preview.");
    
    // Return a mock async iterable with a real audible fallback URL
    async function* mockStream() {
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      yield {
        candidates: [{
          content: {
            parts: [
              { text: params.lyrics || "Simulated lyrics generated by fallback...\n\n(Verse 1)\nIn the neon glow, we find our way..." }
            ]
          }
        }]
      };

      await new Promise(resolve => setTimeout(resolve, 500));

      yield {
        candidates: [{
          content: {
            parts: [
              { inlineData: { mimeType: "audio/mpeg", data: "FALLBACK_AUDIO_SIGNAL" } }
            ]
          }
        }]
      };
    }
    
    return mockStream();
  }
}
